name: Publish to GitHub Packages

on:
  push:
    branches:
      - blue-water-autonomy
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://npm.pkg.github.com"
          scope: "@blue-water-autonomy"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set package name/version/repo
        working-directory: ./packages/openbridge-webcomponents
        run: |
          npm pkg set name="@blue-water-autonomy/openbridge-webcomponents"
          npm pkg set repository.url="git+https://github.com/Blue-Water-Autonomy/openbridge-webcomponents.git"
          base=$(node -p "require('./package.json').version.split('-')[0]")
          version="${base}-bwa.${GITHUB_RUN_NUMBER}"
          npm pkg set version="$version"

      - name: Publish to GitHub Packages
        working-directory: ./packages/openbridge-webcomponents
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --tag latest
